//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnosis()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string Sexual { get; set; }
        public string IdNumber { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public string Symptoms { get; set; }
        public string Advice { get; set; }
        public byte[] Picture { get; set; }
        public int DocterID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime PrintDate { get; set; }
        public string MRN { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
