//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int Id { get; set; }
        public int EmployeeID { get; set; }
        public int PillsID { get; set; }
        public int Count { get; set; }
        public decimal TotalPrice { get; set; }
        public int PatientID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Pill Pill { get; set; }
        public virtual Diagnosis Diagnosi { get; set; }
    }
}
